version: '3.7'

services:
  mysql_db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: planes
    restart: unless-stopped
  flight_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/planes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
    ports:
      - 8081:8081
    restart: on-failure
    links:
      - mysql_db