version: '3.7'

services:
  mysql_db:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flights
    restart: on-failure
  flight_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql_db:3306/flights
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=secret
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mysql_db
volumes:
  mysql_db_data: